### ISSUE TITLE
nixpkgs-fmt hook doesn't respect `.ignore`

### ISSUE THREAD

**Issue by lovesegfault** [cachix/pre-commit-hooks.nix#70]
One of the nice things about `nixpkgs-fmt` is that it respects `.ignore`, which allow you to exclude certain files from the formatter, so they don't get picked up by `nixpkgs-fmt .`. Currently this behavior is broken in `pre-commit-hooks.nix` as, if I understand it, it takes the responsibility of finding/selecting files _away_ from `nixpkgs-fmt` and onto itself, passing it a file list.

This is especially annoying when using tools like `niv` which have a generated Nix file that isn't formatted to `nixpkgs-fmt`'s liking.

**Comment by roberth** [comment]
This is best solved in https://github.com/pre-commit/pre-commit because this project is only a configuration and package management frontend for it.

**Comment by lovesegfault** [comment]
AIUI the only way to exclude certain files is to add an `exclude` clause in `.pre-commit-config.yaml`, which this project auto-generates, so the mechanism to set that has to exist here?

**Comment by roberth** [comment]
The `excludes` field is already supported per hook and globally.

Perhaps an alternative is to invoke `nixpkgs-fmt` once without passing filenames so it can do its own thing. That way pre-commit can't optimize the run based on which files have changed though.
Ideally, support for a `.ignore` file is added in `pre-commit` so that all hooks support it and the optimization isn't lost.

**Comment by lovesegfault** [comment]
Aha, I just had to learn how to use `excludes`, solves it for me. Cheers!
